m3-w8d1-controllers-part1-solution/GetExercises.Web/Models/Actor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GetExercises.Web.Models
{
    public class Actor
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}

m3-w8d1-controllers-part1-solution/GetExercises.Web/Models/ActorSearch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GetExercises.Web.Models
{
    public class ActorSearch
    {
        public string LastName { get; set; }

        public IList<Actor> Results { get; set; } = new List<Actor>();
    }
}

m3-w8d1-controllers-part1-solution/GetExercises.Web/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GetExercises.Web.Models
{
    public class Customer
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
    }
}

m3-w8d1-controllers-part1-solution/GetExercises.Web/Models/CustomerSearch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetExercises.Web.Models
{
    public class CustomerSearch
    {
        public string Name { get; set; }
        public string SortByColumn { get; set; }

        public IList<SelectListItem> SortOptions { get; set; } = new List<SelectListItem>()
        {
            new SelectListItem() { Text = "Last Name", Value = "last_name" },
            new SelectListItem() { Text = "Email", Value = "email" },
            new SelectListItem() { Text = "Active", Value = "active"}
        };


        public IList<Customer> Results { get; set; } = new List<Customer>();
    }
}

m3-w8d1-controllers-part1-solution/GetExercises.Web/Models/Film.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GetExercises.Web.Models
{
    public class Film
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public int ReleaseYear { get; set; }
        public int Length { get; set; }
        public string Rating { get; set; }
    }
}

m3-w8d1-controllers-part1-solution/GetExercises.Web/Models/FilmSearch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetExercises.Web.Models
{
    public class FilmSearch
    {
        public int? MinimumLength { get; set; }
        public int? MaximumLength { get; set; }
        public string Genre { get; set; }
        public List<SelectListItem> Genres { get; set; } = new List<SelectListItem>()
        {
            new SelectListItem{ Text = "Comedy", Value="Comedy" },
            new SelectListItem{ Text = "Action", Value = "Action" },
            new SelectListItem{ Text = "Horror", Value = "Horror" },
            new SelectListItem{ Text = "Family", Value = "Family" },
            new SelectListItem{ Text = "Drama", Value = "Drama" },
        };

        public IList<Film> Results { get; set; } = new List<Film>();
    }
}

m3-w8d1-controllers-part1-solution/GetExercises.Web/Controllers/ActorController.cs
using GetExercises.Web.DAL.Interfaces;
using GetExercises.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetExercises.Web.Controllers
{
    public class ActorController : Controller
    {
        private IActorDAL dal;

        /// <summary>
        /// The MVC framework with the assistance of Ninject, automatically passes in a ActorDAL.
        /// </summary>
        /// <param name="dal"></param>
        public ActorController(IActorDAL dal)
        {
            this.dal = dal;
        }
        
        /// <summary>
        /// The request to display an empty search page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View("Index", new ActorSearch());
        }

        /// <summary>
        /// The request to display search results.
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult SearchResult(ActorSearch request)
        {
            IList<Actor> actors = dal.FindActors(request.LastName);
            request.Results = actors;

            return View("Index", request);
        }
    }
}

m3-w8d1-controllers-part1-solution/GetExercises.Web/Controllers/CustomerController.cs
using GetExercises.Web.DAL.Interfaces;
using GetExercises.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetExercises.Web.Controllers
{
    public class CustomerController : Controller
    {
        private ICustomerDAL dal;

        /// <summary>
        /// The MVC framework with the assistance of Ninject, automatically passes in a CustomerDAL.
        /// </summary>
        /// <param name="dal"></param>
        public CustomerController(ICustomerDAL dal)
        {
            this.dal = dal;
        }

        public ActionResult Index()
        {
            return View("Index", new CustomerSearch());
        }

        public ActionResult SearchResult(CustomerSearch request)
        {
            IList<Customer> customers = dal.SearchForCustomers(request.Name, request.SortByColumn);
            request.Results = customers;

            return View("Index", request);
        }
    }
}

m3-w8d1-controllers-part1-solution/GetExercises.Web/Controllers/FilmController.cs
using GetExercises.Web.DAL.Interfaces;
using GetExercises.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetExercises.Web.Controllers
{
    public class FilmController : Controller
    {
        private IFilmDAL dal;

        /// <summary>
        /// The MVC framework with the assistance of Ninject, automatically passes in a FilmDAL.
        /// </summary>
        /// <param name="dal"></param>
        public FilmController(IFilmDAL dal)
        {
            this.dal = dal;
        }

        // GET: Film
        public ActionResult Index()
        {
            return View("Index", new FilmSearch());
        }

        public ActionResult SearchResult(FilmSearch request)
        {                        
            IList<Film> films = dal.GetFilmsBetween(request.Genre, request.MinimumLength.GetValueOrDefault(0), request.MaximumLength.GetValueOrDefault(1000));
            request.Results = films;

            return View("Index", request);
        }
    }
}

m3-w8d1-controllers-part1-solution/GetExercises.Web/Views/Actor/Index.cshtml
@model GetExercises.Web.Models.ActorSearch
@{
    ViewBag.Title = "All Actors List";
}

<form method="get" action="@Url.Action("SearchResult", "Actor")" class="form-inline">
    <div class="form-group">
        <label for="minimumLength">Last Name: </label>
        @Html.TextBoxFor(
                /* 1. Bind the input to the Last Name field. */
                m => m.LastName,

                /* 2. Add a class="form-control" to the html */
                new { @class = "form-control"})
    </div>    
    <input class="btn btn-default" style="margin-top: 25px;" name="search" value="Search" type="submit" />
</form>
<table class="table">
    <tr>
        <th>Name</th>        
    </tr>
    @foreach (var actor in Model.Results)
    {
        <tr>
            <td>@actor.FirstName @actor.LastName</td>            
        </tr>
    }
</table>

m3-w8d1-controllers-part1-solution/GetExercises.Web/Views/Film/Index.cshtml
@model GetExercises.Web.Models.FilmSearch
@{
    ViewBag.Title = "All Films List";
}

<form method="get" action="@Url.Action("SearchResult", "Film")" class="form-inline">
    <div class="form-group">
        <label for="minimumLength">Minimum Length: </label>
        @Html.TextBoxFor(
                /* 1. Save the value to the MinimumLength property */
                m => m.MinimumLength, 

                /* 2. Add a class="form-control" type="number" to the html */
                new { @class = "form-control", type = "number"})
    </div>
    <div class="form-group">
        <label for="minimumLength">Maximum Length: </label>
        @Html.TextBoxFor(

                /* 1. Save the value to the MinimumLength property */
                m => m.MaximumLength, 
                
                /* 2. Add a class="form-control" type="number" to the html */
                new { @class = "form-control", type = "number" })
    </div>
    <div class="form-group">
        <label for="genre">Genre: </label>
        @Html.DropDownListFor(
       
                /* 1. Save the value in the Genre property*/
                m => m.Genre, 
                
                /* 2. Get all of the drop down values from the Genres property*/
                Model.Genres, 
                
                                
                /* 3. Add a class="form-control" to the html */
                new { @class = "form-control" })        
    </div>
    <input class="btn btn-default" style="margin-top: 25px;" name="search" value="Search" type="submit" />
</form>
<table class="table">
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Release Year</th>
        <th>Length</th>
        <th>Rating</th>
    </tr>
    @foreach (var film in Model.Results)
    {
        <tr>
            <td>@film.Title</td>
            <td>@film.Description</td>
            <td>@film.ReleaseYear</td>
            <td>@film.Length</td>
            <td>@film.Rating</td>
        </tr>
    }
</table>