m3-w7-ssgeek-solution/SSGeek/Controllers/CalculatorsController.cs
using SSGeek.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSGeek.Controllers
{
    public class CalculatorsController : Controller
    {
        // INSTRUCTIONS
        // As a part of each exercise you will need to 
        // - develop a view for AlienAge, AlienWeight, and AlienTravel that displays a form to submit data
        // - create a new action to process the form submission (e.g. AlienAgeResult, AlienWeightResult, etc.)
        // - create a view that displays the submitted form result

        // GET: Calculators/AlienAge
        public ActionResult AlienAge()
        {
            ViewBag.PlanetList = planets;

            return View("AlienAge", new AlienAgeModel());
        }

        public ActionResult AlienAgeResult(AlienAgeModel model)
        {            
            return View("AlienAgeResult", model);
        }

        // GET: Calculators/AlienWeight
        public ActionResult AlienWeight()
        {
            ViewBag.PlanetList = planets;

            return View("AlienWeight", new AlienWeightModel());
        }

        public ActionResult AlienWeightResult(AlienWeightModel model)
        {            
            return View("AlienWeightResult", model);
        }

        // GET: Calculators/AlienTravel
        public ActionResult AlienTravel()
        {
            ViewBag.PlanetList = planets;
            ViewBag.TransportationModes = transportationModes;

            return View("AlienTravel", new AlienTravelModel());
        }

        public ActionResult AlienTravelResult(AlienTravelModel model)
        {            
            return View("AlienTravelResult", model);
        }

        private List<SelectListItem> planets = new List<SelectListItem>()
        {
            new SelectListItem() { Text = "Mercury" },
            new SelectListItem() { Text = "Venus" },
            new SelectListItem() { Text = "Mars" },
            new SelectListItem() { Text = "Jupiter" },
            new SelectListItem() { Text = "Saturn" },
            new SelectListItem() { Text = "Neptune" },
            new SelectListItem() { Text = "Uranus" }
        };

        private List<SelectListItem> transportationModes = new List<SelectListItem>()
        {
            new SelectListItem() { Text = "Walking", Value="walking" },
            new SelectListItem() { Text = "Car", Value = "car" },
            new SelectListItem() { Text = "Bullet Train", Value = "bullet train" },
            new SelectListItem() { Text = "Boeing 747", Value = "boeing 747" },
            new SelectListItem() { Text = "Concorde", Value = "concorde" }
        };
    }
}

m3-w7-ssgeek-solution/SSGeek/Controllers/ForumController.cs
using SSGeek.DAL;
using SSGeek.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSGeek.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForumPostDAL forumDal;

        public ForumController(IForumPostDAL forumDal)
        {
            this.forumDal = forumDal;
        }


        // GET: Forum
        public ActionResult Index()
        {
            List<ForumPost> posts = forumDal.GetAllPosts();
            return View("Index", posts);
        }

        public ActionResult NewPost()
        {
            return View("NewPost", new ForumPost());
        }

        [HttpPost]
        public ActionResult NewPost(ForumPost post)
        {
            var result = forumDal.SaveNewPost(post);

            TempData["Message_Success"] = true;

            return RedirectToAction("Index");
        }

    }
}

m3-w7-ssgeek-solution/SSGeek/Controllers/StoreController.cs
using SSGeek.DAL;
using SSGeek.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSGeek.Controllers
{
    public class StoreController : Controller
    {
        private const string ShoppingCart_SessionKey = "ShoppingCart";
        private readonly IProductDAL productDal;

        public StoreController(IProductDAL productDal)
        {
            this.productDal = productDal;
        }

        // GET: Store
        public ActionResult Index()
        {
            var products = productDal.GetProducts();
            return View("Index", products);
        }

        // GET: Store/Detail/id
        public ActionResult Detail(int id)
        {
            // Check to make sure that the id is for a valid product
            var product = productDal.GetProduct(id);

            if (product == null)
            {
                return new HttpNotFoundResult(); //404
            }

            return View("Detail", product);
        }

        [HttpPost]
        public ActionResult AddToCart(int productId, int quantity)
        {
            // Check to make sure that they are purchasing a valid product
            var product = productDal.GetProduct(productId);

            if (product== null)
            {
                return new HttpNotFoundResult();
            }

            // Check to see if a shopping cart exists in session, if not create it
            if (Session[ShoppingCart_SessionKey] == null)
            {
                Session[ShoppingCart_SessionKey] = new ShoppingCart();
                }

            // Retrieve the cart from session
            var shoppingCart = (ShoppingCart)Session[ShoppingCart_SessionKey];

            // Add the product or update the quantity
            shoppingCart.AddOrUpdateCart(product, quantity);

            // Store cart back in session
            Session[ShoppingCart_SessionKey] = shoppingCart;

            return RedirectToAction("ViewCart");
        }

        // GET: Store/ViewCart
        public ActionResult ViewCart()
        {            
            ShoppingCart model = new ShoppingCart();

            // Retrieve cart from session
            if (Session[ShoppingCart_SessionKey] != null)
            {
                model = (ShoppingCart)Session[ShoppingCart_SessionKey];
            }

            return View("ViewCart", model);
        }


    }
}

m3-w7-ssgeek-solution/SSGeek/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Solar System Geek</title>
    <link rel="stylesheet" href="~/Content/solarsystemgeek.css">
</head>

<body>
    <header>
        <img src="~/Content/img/ssg_logo.png" alt="Solar System Geek logo" />
        <h1>The Solar System</h1>
        <p>The Solar System formed 4.6 billion years ago from the gravitational collapse of a giant interstellar molecular cloud. The vast majority of the system's mass is in the Sun, with most of the remaining mass contained in Jupiter. The four smaller inner planets, Mercury, Venus, Earth and Mars, are terrestrial planets, being primarily composed of rock and metal. The four outer planets are giant planets, being substantially more massive than the terrestrials. The two largest, Jupiter and Saturn, are gas giants, being composed mainly of hydrogen and helium; the two outermost planets, Uranus and Neptune, are ice giants, being composed largely of substances with relatively high melting points compared with hydrogen and helium, called ices, such as water, ammonia and methane. All planets have almost circular orbits that lie within a nearly flat disc called the ecliptic. </p>
    </header>
    <nav>
        <h2>Explore The Solar System</h2>
        <p> Use these state of the art web applications to learn more about the solar system! </p>
        <ul>
            <li>@Html.ActionLink("Alien Age", "AlienAge", "Calculators")</li>
            <li>@Html.ActionLink("Alien Weight", "AlienWeight", "Calculators")</li>
            <li>@Html.ActionLink("Alien Travel Time", "AlienTravel", "Calculators")</li>   
            <li>@Html.ActionLink("Space Forum", "Index", "Forum")</li>     
            <li>@Html.ActionLink("Space Store", "Index", "Store")</li>            
        </ul>
    </nav>

    @RenderBody()

</body>
</html>